### ISSUE TITLE
It only auto reloads when I hit ctrl-s to save.

### ISSUE THREAD

**Issue by ZACit** [negokaz/vscode-live-server-preview#1]
The preview shows it updating changes on the fly, after a fresh install I only get it to update after hitting ctrl-s to save.

**Comment by negokaz** [comment]
@ZACit 
The preview shows changes after saving file. You can show it on the fly by setting `files.autoSave` to `true`. If the delay before changes is reflected is too long, you can adjust it by setting `file.autoSaveDelay`.
