### ISSUE TITLE
Error: Cannot GET /y/index.html

### ISSUE THREAD

**Issue by ljones87** [negokaz/vscode-live-server-preview#4]
Hello,
 I just installed your extension today  (10.7.17) and I'm getting an error when the extension opens in a second window with the message  "Cannot GET /y/index.html."
<img width="1125" alt="screen shot 2017-10-07 at 3 32 38 pm" src="https://user-images.githubusercontent.com/27159818/31311952-ceb3b6c2-ab74-11e7-9d3f-4da264d39c9f.png">

My HTML file opens will no issue in a browser.
Not sure if I am doing something incorrectly?

I launched using shift+command+p to bring up the command pallet and typed "show live" which populates Show Live Server Preview.

**Comment by TennChris** [comment]
I have the same problem on one computer. Other computer is fine. Not sure what I did differently in the setup. Did you ever find a solution to this? Thanks!

**Comment by ljones87** [comment]
@TennChris unfortunately I did not. Pretty sure I abandoned set up and use the browser. Might revisit again now, try to uninstall and reinstall the extension. I'll post here if I resolve the problem.

**Comment by ljones87** [comment]
@TennChris so I just uninstalled and re-installed the extension and it's working perfectly now. Silly I didn't try that to begin with. Must have been a weird install bug the first round. Gotta love easy fixes.

**Comment by magi1919** [comment]
@ljones87 I experienced the same that situation. also, 1) just uninstalled this extension and 2) Quit VS Code 3) Open the VS Code 4) re-installed that extension. : now that extension is working perfectly.

**Comment by catnipped** [comment]
I have the same error!

**Comment by mjyousse** [comment]
Anyone found solution for this issue? it doesn't seem to be working for me. I tried everything but it's giving me that same error.

**Comment by optionsquant** [comment]
same problem ,no solution, tried reinstall vs code

**Comment by CountElqyd** [comment]
Try to rename folders and file names. Mine shows the same error when I have invalid characters in my files and folders like "?".
Other than that Live server works normally.

**Comment by mohdnneloy** [comment]
I solved it! Please Make sure that your directory in which the index.html is stored is not named with any Symbol like "!@#$%^&*()". Try to name your directory or folder with letters only. For example, "Time and Date"

In your case, I think you have to remove the extra "/" from your directory "/y".

**Comment by AdityaKrishnamurthy** [comment]
Woahhhh Thanks a ton @mohdnneloy worked perfectly i was pissed off with that "Cannot GET" error,  i just removed the symbols of the .html fine and voila worked perfectly! thanks a lot again

**Comment by mohdnneloy** [comment]
@AdityaK1104 You're Most Welcome!
