### ISSUE TITLE
Confusion between \ and / for paths

### ISSUE THREAD

**Issue by andersonaddo** [negokaz/vscode-live-server-preview#7]
![2018-01-26](https://user-images.githubusercontent.com/34724755/35430434-1ede948a-0270-11e8-8f93-7608c528b827.png)
The program seems to only be able to recognize paths that separate entities with /. I think there should be a way to toggle either / or \ for path separation.

**Comment by optionsquant** [comment]
> @andersonaddo Thank you for your feedback!
> I improved path resolving in v0.1.2. Please try the version.

which version ?  vscode version or  plug version
