### ISSUE TITLE
Cannot GET /index.html

### ISSUE THREAD

**Issue by pavilion** [negokaz/vscode-live-server-preview#8]
I try to F1 -> Show live server preview and this appears...

![image](https://user-images.githubusercontent.com/3165436/36057044-af397990-0e01-11e8-98a6-bf4f4716950a.png)

Using v.1.21.0-insider

**Comment by LizKeay** [comment]
I am getting the same issue. I've reinstalled vscode with version 1.20.1 and reinstalled the preview plugin.

**Comment by pavilion** [comment]
@LizKeay use https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer instead

**Comment by andersonaddo** [comment]
#7 I think the issue is coming from the fact that pro program is confused between / path separators and \ path separators.

**Comment by Almenon** [comment]
I got this issue when I had two workspaces open.  Switching to just one workspace fixed it.

**Comment by Dmitri801** [comment]
Hi, I'm having this same exact issue, I only have 1 workspace open. also when I try to use  https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer: 

It says it needs a body and html tag, but the html does have a body and html tag. any thoughts or solutions?

**Comment by negokaz** [comment]
Sorry for the late reply.
I will work on this issue.

**Comment by LizKeay** [comment]
Thanks - issue resolved for me.

**Comment by bilaljaved786** [comment]
> Thanks - issue resolved for me.

how you solved it

**Comment by HarryAdney** [comment]
In case it helps anyone else, I originally named my distribution folder as "public_html" and got this error. I renamed it to "public" and updated the config files, etc. restarted VS Code and it worked fine.

**Comment by lolaloka** [comment]
rename it to another name and it will work fine

**Comment by piotrekja** [comment]
Yes, it works only for files from one workspace (one ancestor folder). The best way to check where it is busy/blocked is by pasting http://localhost:8080/ into your browser. Close everything in your workspace open again where you want it and that will sort it

**Comment by GWBSU** [comment]
I had this issue and solved it by removing special characters from my file name.  I had a file with #2 in the name, I removed the # from the title and everything worked fine.

**Comment by Redyier** [comment]
If you are using live server on Explorer go to Live share and under section Shared Servers just click on Live Server.

![image](https://user-images.githubusercontent.com/71843053/99424996-9caa1e00-2902-11eb-8ba3-dbc8f95fc0b6.png)

**Comment by piotrekja** [comment]
I had that message when another file was opened in that extension. Just close all the folders in the File menu of the VScode and that should solve it.

**Comment by vahidavadiya** [comment]
Thank you @ccomstudio I had the same issue in folder name I have used '&' removing special character solved my problem.

**Comment by harshgajera101** [comment]
I had just disable all the extensions which were working , and then i enabled it again and it started working as same as before..
I think this might help you.

**Comment by Umama-Nayyer** [comment]
i were stuck with the same issue but resolved it finally.
here is how:
i were only opening my file which is "index.html" in visual studio code but then i closed the file and opened the folder which contains that file in vs code. after that i used " open with live server by right clicking " and here it worked.

**Comment by alexanderhipe** [comment]
> 
> 
> I got this issue when I had two workspaces open. Switching to just one workspace fixed it.

Same as mine, so it means that the live server will work only for 1 workspace..

**Comment by ShubhamBohra0009** [comment]
I had the same problem but here is the solution .
 The file you're trying to see through live server might be in a folder which is co-folder of some other folder let say folder name A. And this problem arise when we open the vscode through folder A rather than the exact co-folder in which our file exist. so just close the vscode. open it in that particular co-folder and you're good to go. :)

**Comment by ZackInMA** [comment]
It seems the issue is that if the path contains JavaScript keywords, it breaks. 
![Screenshot](https://user-images.githubusercontent.com/55891488/144158190-c3e5617f-c277-4c44-a72d-cd9897a1b2ed.png)

Red = broken. Green works. 

The difference? The broken one contains the JavaScript keywords LET and CONST in the path... That's the only difference I can see. I validated this by renaming the folder to "test" and it worked after that. So the folder name having JS keywords seems to be the issue here.

**Comment by kaioqrz** [comment]
> I had this issue and solved it by removing special characters from my file name. I had a file with #2 in the name, I removed the # from the title and everything worked fine.

thanks!!!

**Comment by Mac4ttack** [comment]
I just ran into this issue and it was the "&" in the folder name. Changed to "and" fixed all issues.

Previously, with the "&" I could still use the option to "Go Live" in the bottom right corner of VSC and navigate to the index.html in that folder name and it worked fine. However, right-clicking to "Open with live server" ended in an Error: Cannot GET /HTML%20%5E&%20CSS/x/index.html


> It seems the issue is that if the path contains JavaScript keywords, it breaks. ![Screenshot](https://user-images.githubusercontent.com/55891488/144158190-c3e5617f-c277-4c44-a72d-cd9897a1b2ed.png)
> 
> Red = broken. Green works.
> 
> The difference? The broken one contains the JavaScript keywords LET and CONST in the path... That's the only difference I can see. I validated this by renaming the folder to "test" and it worked after that. So the folder name having JS keywords seems to be the issue here.

**Comment by stoicfeats** [comment]
A very simple change worked for me, just try changing your folder name in which your files are present, sometimes if your folder container has too many symbols and characters with spaces in it, change it to something simple without many characters.
Especially the '&' character.

**Comment by Shaimaa-Hassan** [comment]
i have the same problem i still can not solve it

**Comment by Brendan-A-Wilson** [comment]
@busybee23 Thanks, that worked for me. The '&' character in the folder name was the issue for me.

**Comment by onwuemenejoshua** [comment]
I resolved mine by removing the special character "&" from my folder name

**Comment by stoicfeats** [comment]
> @busybee23 Thanks, that worked for me. The '&' character in the folder name was the issue for me.

No worries sir.

**Comment by Anandkokane** [comment]
you created index.html file which is resides in  (eg:xyz) folder.
next when you was trying to open that file with the help of live server you got the error like 404 can't get
i had also facing the same error but after passed 30 min i got it solution 
let's go look a few steps 
1)you got an error cause you only putinig filename in path 
![error1](https://user-images.githubusercontent.com/105542678/189285718-968caa88-a676-4887-b2c8-6e7ef2d1fc5c.png)

2)but you created index.html file it's actually resides in Project folder(folder name can be anything )
![error2](https://user-images.githubusercontent.com/105542678/189286101-009675a8-ace8-44e6-ab53-ca8c0a74a54f.png)

3)you have to put full path in your browser just like this (/foldername/filename) after that you will render the your index.html page.
![error3](https://user-images.githubusercontent.com/105542678/189286398-6ed3061c-b58a-4f97-82eb-6befcc9da2c2.png)

Thank you :)

**Comment by gentiles** [comment]
just update the vscode

**Comment by Dumte** [comment]
who got a solution to this problem? i'm having the same issue

**Comment by Danyllo-Mendanha-dev** [comment]
Basta você renomear o arquivo index.html  , pois pode estar ocorrendo um sobrepujamento de arquivos com nomes iguais, nesse caso (index.html), assim é só salvar o novo nome do arquivo e executar o servidor "LiveServer".

**Comment by theMHD-120** [comment]
> #7 I think the issue is coming from the fact that pro program is confused between / path separators and \ path separators.

Thank you very much bro...
I had used & (ampersand) in one of my repository folders and got this error...
By changing it, my problem was solved! :) 
...

**Comment by codingwalebhaiya** [comment]
I solved this issue by removing special characters like &. 
my folder name before issue - drag & drop
my folder name after resolving the issue - drag and drop

**Comment by Hamza-Codez** [comment]
**The solution** ! I got for the same Problem.
I was also fed up retrying and finding out what's wrong with my _code/ live server_ ! I also used Ampersand (&) in naming my local repository file....
**Avoid** This **(&)** guys.... **in naming your repositories**.
